version: '3'
services:
  web:
    build: .
    ports:
      - "3030:3000"
    links:
      - db
    volumes:
      - ./docker.ormconfig.json:/usr/src/app/ormconfig.json
  db:
    image: mysql:5
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: todoist
      MYSQL_PASSWORD: todoist
      MYSQL_DATABASE: todoist